name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpunit
      - run: composer install --no-progress --no-suggest --prefer-dist
      - run: vendor/bin/phpunit --configuration phpunit.xml
